const mockVeiculos = [
  {
    id: 1,
    placa: "ABC-1234",
    proprietario: "João Silva",
    matricula: "2024001",
    modelo: "Honda Civic",
    status: "estacionado",
  },
  {
    id: 2,
    placa: "DEF-5678",
    proprietario: "Maria Santos",
    matricula: "2024002",
    modelo: "Toyota Corolla",
    status: "ausente",
  },
  {
    id: 3,
    placa: "GHI-9012",
    proprietario: "Pedro Costa",
    matricula: "2024003",
    modelo: "Fiat Uno",
    status: "estacionado",
  },
  {
    id: 4,
    placa: "JKL-3456",
    proprietario: "Ana Lima",
    matricula: "2024004",
    modelo: "VW Gol",
    status: "ausente",
  },
  {
    id: 5,
    placa: "MNO-7890",
    proprietario: "Carlos Rocha",
    matricula: "2024005",
    modelo: "Chevrolet Onix",
    status: "estacionado",
  },
  {
    id: 6,
    placa: "PQR-2345",
    proprietario: "Lucia Ferreira",
    matricula: "2024006",
    modelo: "Renault Kwid",
    status: "estacionado",
  },
  {
    id: 7,
    placa: "STU-6789",
    proprietario: "Rafael Mendes",
    matricula: "2024007",
    modelo: "Hyundai HB20",
    status: "ausente",
  },
  {
    id: 8,
    placa: "VWX-0123",
    proprietario: "Beatriz Neves",
    matricula: "2024008",
    modelo: "Jeep Renegade",
    status: "estacionado",
  },
  {
    id: 9,
    placa: "SRT-0249",
    proprietario: "Arthur Rodrigues",
    matricula: "2025010",
    modelo: "Fusca",
    status: "ausente",
  },
  {
    id: 10,
    placa: "SRT-0798",
    proprietario: "Gabriel Costa",
    matricula: "2025202",
    modelo: "Celta",
    status: "estacionado",
  },
  {
    id: 9,
    placa: "SRT-0249",
    proprietario: "Arthur Rodrigues",
    matricula: "2025010",
    modelo: "Fusca",
    status: "ausente",
  },
];

const mockMovimentacoes = [
  {
    id: 1,
    placa: "ABC-1234",
    tipo: "entrada",
    horario: "08:02",
    permanencia: null,
    status: "estacionado",
    foto: "../assets/images/placa-carro.jpg",
  },
  {
    id: 2,
    placa: "PQR-2345",
    tipo: "entrada",
    horario: "08:15",
    permanencia: null,
    status: "estacionado",
    foto: "../assets/images/placa-carro.jpg",
  },
  {
    id: 3,
    placa: "DEF-5678",
    tipo: "entrada",
    horario: "08:30",
    permanencia: null,
    status: "estacionado",
    foto: "../assets/images/placa-carro.jpg",
  },
  {
    id: 4,
    placa: "DEF-5678",
    tipo: "saida",
    horario: "09:45",
    permanencia: "1h 15min",
    status: "ausente",
    foto: "../assets/images/placa-carro.jpg",
  },
  {
    id: 5,
    placa: "GHI-9012",
    tipo: "entrada",
    horario: "10:00",
    permanencia: null,
    status: "estacionado",
    foto: "../assets/images/placa-carro.jpg",
  },
  {
    id: 6,
    placa: "JKL-3456",
    tipo: "entrada",
    horario: "10:20",
    permanencia: null,
    status: "estacionado",
    foto: "../assets/images/placa-carro.jpg",
  },
  {
    id: 7,
    placa: "JKL-3456",
    tipo: "saida",
    horario: "11:50",
    permanencia: "1h 30min",
    status: "ausente",
    foto: "../assets/images/placa-carro.jpg",
  },
  {
    id: 8,
    placa: "MNO-7890",
    tipo: "entrada",
    horario: "12:05",
    permanencia: null,
    status: "estacionado",
    foto: "../assets/images/placa-carro.jpg",
  },
  {
    id: 9,
    placa: "STU-6789",
    tipo: "entrada",
    horario: "13:10",
    permanencia: null,
    status: "estacionado",
    foto: "../assets/images/placa-carro.jpg",
  },
  {
    id: 10,
    placa: "STU-6789",
    tipo: "saida",
    horario: "14:30",
    permanencia: "1h 20min",
    status: "ausente",
    foto: "../assets/images/placa-carro.jpg",
  },
];

const mockUsuarios = [
  {
    id: 1,
    matricula: "0101",
    nome: "João Silva",
    email: "joao.silva@ugb.edu.br",
    role: "admin",
  },
  {
    id: 2,
    matricula: "0202",
    nome: "Maria Santos",
    email: "maria.santos@ugb.edu.br",
    role: "colaborador",
  },
  {
    id: 3,
    matricula: "0303",
    nome: "Pedro Costa",
    email: "pedro.costa@ugb.edu.br",
    role: "colaborador",
  },
  {
    id: 4,
    matricula: "0404",
    nome: "Ana Lima",
    email: "ana.lima@ugb.edu.br",
    role: "colaborador",
  },
];

const mockDashboard = {
  veiculosNoEstacionamento: mockVeiculos.filter(
    (v) => v.status === "estacionado",
  ).length,
  entradasDoDia: mockMovimentacoes.filter((m) => m.tipo === "entrada").length,
  saidasDoDia: mockMovimentacoes.filter((m) => m.tipo === "saida").length,
  vagasDisponiveis: mockVeiculos.filter((v) => v.status === "ausente").length,
  vagasTotal: 100,
};

export { mockDashboard, mockVeiculos, mockMovimentacoes, mockUsuarios };
